package com.models;
// Generated 7 f�vr. 2017 11:34:38 by Hibernate Tools 5.2.0.Beta1

/**
 * AAutomateProduit generated by hbm2java
 */
public class AAutomateProduit implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private AAutomateProduitId id;
	private Produit produit;
	private Rapport rapport;
	private Integer quantite;

	public AAutomateProduit() {
	}

	public AAutomateProduit(AAutomateProduitId id, Produit produit, Rapport rapport) {
		this.id = id;
		this.produit = produit;
		this.rapport = rapport;
	}

	public AAutomateProduit(AAutomateProduitId id, Produit produit, Rapport rapport, Integer quantite) {
		this.id = id;
		this.produit = produit;
		this.rapport = rapport;
		this.quantite = quantite;
	}

	public AAutomateProduitId getId() {
		return this.id;
	}

	public void setId(AAutomateProduitId id) {
		this.id = id;
	}

	public Produit getProduit() {
		return this.produit;
	}

	public void setProduit(Produit produit) {
		this.produit = produit;
	}

	public Rapport getRapport() {
		return this.rapport;
	}

	public void setRapport(Rapport rapport) {
		this.rapport = rapport;
	}

	public Integer getQuantite() {
		return this.quantite;
	}

	public void setQuantite(Integer quantite) {
		this.quantite = quantite;
	}

}
