package com.models;
// Generated 7 f�vr. 2017 11:34:38 by Hibernate Tools 5.2.0.Beta1

/**
 * ARapportProduit generated by hbm2java
 */
public class ARapportProduit implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private ARapportProduitId id;
	private Produit produit;
	private Rapport rapport;
	private Integer quantite;

	public ARapportProduit() {
	}

	public ARapportProduit(ARapportProduitId id, Produit produit, Rapport rapport) {
		this.id = id;
		this.produit = produit;
		this.rapport = rapport;
	}

	public ARapportProduit(ARapportProduitId id, Produit produit, Rapport rapport, Integer quantite) {
		this.id = id;
		this.produit = produit;
		this.rapport = rapport;
		this.quantite = quantite;
	}

	public ARapportProduitId getId() {
		return this.id;
	}

	public void setId(ARapportProduitId id) {
		this.id = id;
	}

	public Produit getProduit() {
		return this.produit;
	}

	public void setProduit(Produit produit) {
		this.produit = produit;
	}

	public Rapport getRapport() {
		return this.rapport;
	}

	public void setRapport(Rapport rapport) {
		this.rapport = rapport;
	}

	public Integer getQuantite() {
		return this.quantite;
	}

	public void setQuantite(Integer quantite) {
		this.quantite = quantite;
	}

}
