package com.models;
// Generated 7 f�vr. 2017 11:34:38 by Hibernate Tools 5.2.0.Beta1

import java.util.Date;

/**
 * ErreurId generated by hbm2java
 */
public class ErreurId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String nom;
	private Date date;
	private int rapportId;
	private int numSerie;

	public ErreurId() {
	}

	public ErreurId(String nom, Date date, int rapportId, int numSerie) {
		this.nom = nom;
		this.date = date;
		this.rapportId = rapportId;
		this.numSerie = numSerie;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public int getRapportId() {
		return this.rapportId;
	}

	public void setRapportId(int rapportId) {
		this.rapportId = rapportId;
	}

	public int getNumSerie() {
		return this.numSerie;
	}

	public void setNumSerie(int numSerie) {
		this.numSerie = numSerie;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ErreurId))
			return false;
		ErreurId castOther = (ErreurId) other;

		return ((this.getNom() == castOther.getNom())
				|| (this.getNom() != null && castOther.getNom() != null && this.getNom().equals(castOther.getNom())))
				&& ((this.getDate() == castOther.getDate()) || (this.getDate() != null && castOther.getDate() != null
						&& this.getDate().equals(castOther.getDate())))
				&& (this.getRapportId() == castOther.getRapportId()) && (this.getNumSerie() == castOther.getNumSerie());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getNom() == null ? 0 : this.getNom().hashCode());
		result = 37 * result + (getDate() == null ? 0 : this.getDate().hashCode());
		result = 37 * result + this.getRapportId();
		result = 37 * result + this.getNumSerie();
		return result;
	}

}
