package com.models;
// Generated 7 f�vr. 2017 11:34:38 by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * Produit generated by hbm2java
 */
public class Produit implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String nom;
	private String type;
	private Set<AAutomateProduit> AAutomateProduits = new HashSet<AAutomateProduit>(0);

	public Produit() {
	}

	public Produit(String nom, String type) {
		this.nom = nom;
		this.type = type;
	}

	public Produit(String nom, String type, Set<AAutomateProduit> AAutomateProduits) {
		this.nom = nom;
		this.type = type;
		this.AAutomateProduits = AAutomateProduits;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Set<AAutomateProduit> getAAutomateProduits() {
		return this.AAutomateProduits;
	}

	public void setAAutomateProduits(Set<AAutomateProduit> AAutomateProduits) {
		this.AAutomateProduits = AAutomateProduits;
	}

}
