package com.models;
// Generated 7 f�vr. 2017 11:34:38 by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Entity;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Produit generated by hbm2java
 */
@Entity
@XmlRootElement(name="Produit")
public class Produit implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String nom;
	private String type;
	//private Set<ARapportProduit> ARapportsProduits = new HashSet<ARapportProduit>(0);

	public Produit() {
	}

	public Produit(String nom, String type) {
		this.nom = nom;
		this.type = type;
	}

//	public Produit(String nom, String type, Set<ARapportProduit> ARapportProduits) {
//		this.nom = nom;
//		this.type = type;
//		this.ARapportsProduits = ARapportProduits;
//	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

//	public Set<ARapportProduit> getARapportProduits() {
//		return this.ARapportsProduits;
//	}
//
//	public void setARapportProduits(Set<ARapportProduit> ARapportProduits) {
//		this.ARapportsProduits = ARapportProduits;
//	}

}
