package com.models;
// Generated 7 f�vr. 2017 11:34:38 by Hibernate Tools 5.2.0.Beta1

/**
 * RapportId generated by hbm2java
 */
public class RapportId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int rapportId;
	private int numSerie;

	public RapportId() {
	}

	public RapportId(int rapportId, int numSerie) {
		this.rapportId = rapportId;
		this.numSerie = numSerie;
	}

	public int getRapportId() {
		return this.rapportId;
	}

	public void setRapportId(int rapportId) {
		this.rapportId = rapportId;
	}

	public int getNumSerie() {
		return this.numSerie;
	}

	public void setNumSerie(int numSerie) {
		this.numSerie = numSerie;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RapportId))
			return false;
		RapportId castOther = (RapportId) other;

		return (this.getRapportId() == castOther.getRapportId()) && (this.getNumSerie() == castOther.getNumSerie());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRapportId();
		result = 37 * result + this.getNumSerie();
		return result;
	}

}
